#!/bin/bash

git config pull.rebase false
export GIT_MERGE_AUTOEDIT=no

git add .
git commit -m "Local changes before sync"

git pull

git push

if ! git pull origin flutterflow; then
	exit 1 # break execution if GIT conflict occured
fi

if [ "$DEEP" = true ] ; then

  flutter pub get
  flutter pub run flutter_launcher_icons
  
fi

git add .
git commit -m "Local changes after sync"
git push
